name: nahej_ali
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  sqflite: ^2.4.1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logoNA.png
    - assets/images/nahej.jpeg
    - assets/images/donorlogo.png
    - assets/images/admin.png
    - assets/images/volunteers.png
    - assets/images/temp-02.jpg
    - assets/images/temp-03.jpg
    - assets/images/home.png
